name: zlp_jokes
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.4
  intl: any

dev_dependencies:
  analyzer: ^6.2.0
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
